<?php
include 'config.php';
$active='colunas';
function tvs_col_public_json($file){ if(!file_exists($file)) return []; $d=json_decode(file_get_contents($file),true); return is_array($d)?$d:[]; }
function tvs_col_public_h($s){ return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8'); }
function tvs_col_public_excerpt($text,$max=170){ $text=trim(strip_tags((string)$text)); if(function_exists('mb_strlen') && mb_strlen($text,'UTF-8')>$max) return mb_substr($text,0,$max,'UTF-8').'...'; if(strlen($text)>$max) return substr($text,0,$max).'...'; return $text; }
$cols=tvs_col_public_json('data/colunas.json');
$cols=array_values(array_filter($cols,function($c){ return ($c['status']??'published')==='published'; }));
usort($cols,function($a,$b){ return strtotime($b['created_at']??'now') <=> strtotime($a['created_at']??'now'); });
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Colunas Jornalísticas | TV Sumaré</title><meta name="description" content="Opinião, análise e colunas jornalísticas da TV Sumaré."><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/style.css"><link rel="icon" href="assets/logo-tv-sumare.jpeg"></head><body><?php include 'header.php'; ?><main class="container page-shell"><div class="page-title"><span>Opinião e análise</span><h1>Colunas Jornalísticas</h1><p>Artigos, análises e comentários de colunistas da TV Sumaré e convidados.</p></div><div class="news-grid news-grid--wide"><?php if(!$cols): ?><article class="news-card"><div class="news-body"><span class="category-tag">Colunas</span><h3>Nenhuma coluna publicada ainda</h3><p>As colunas aparecerão aqui quando forem cadastradas no painel.</p></div></article><?php endif; ?><?php foreach($cols as $c): ?><article class="news-card"><div class="news-thumb"><img src="<?=tvs_col_public_h($c['image']??$c['author_photo']??'assets/logo-tv-sumare.jpeg')?>" onerror="this.src='assets/logo-tv-sumare.jpeg'" alt=""></div><div class="news-body"><span class="category-tag"><?=tvs_col_public_h($c['category']??'Opinião')?></span><h3><?=tvs_col_public_h($c['title']??'Coluna')?></h3><p><?=tvs_col_public_h($c['subtitle']??$c['summary']??tvs_col_public_excerpt($c['body']??''))?></p><p><strong>Por <?=tvs_col_public_h($c['author']??'Colunista')?></strong></p><a class="btn" href="coluna.php?id=<?=urlencode($c['id']??'')?>">Ler coluna</a></div></article><?php endforeach; ?></div></main><?php include 'rodape.php'; ?></body></html>
