<?php
$active='guia'; require_once __DIR__.'/site_helpers.php'; $msg='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST' && ($_POST['form_type']??'')==='guia'){
  $orders=tvs_read_admin_json('guia_pedidos.json');
  $orders[]=['id'=>uniqid('guia_'),'company'=>tvs_safe_text($_POST['company']??''),'category'=>tvs_safe_text($_POST['category']??''),'description'=>tvs_safe_text($_POST['description']??''),'whatsapp'=>tvs_safe_text($_POST['whatsapp']??''),'address'=>tvs_safe_text($_POST['address']??''),'city'=>tvs_safe_text($_POST['city']??''),'instagram'=>tvs_safe_text($_POST['instagram']??''),'link'=>tvs_safe_text($_POST['link']??''),'image'=>tvs_upload_public_file('image','guia'),'receipt'=>tvs_upload_public_file('receipt','comprovantes'),'status'=>'recebido','created_at'=>date('c')];
  tvs_save_admin_json('guia_pedidos.json',$orders); $msg='Solicitação enviada. A equipe TV Sumaré fará a conferência e aprovação.';
}
$biz=tvs_read_admin_json('empresas.json'); if(!$biz)$biz=[['name'=>'Espaço Comercial Premium','area'=>'Serviços','desc'=>'Cadastre sua empresa no Guia Comercial TV Sumaré.','phone'=>'(19) 97419-8194']];
function h($v){return htmlspecialchars((string)$v);} ?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Guia Comercial | TV Sumaré</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/style.css"></head><body><?php include 'header.php'; ?><main class="container page-shell"><div class="page-title"><span>Empresas & Serviços</span><h1>Guia Comercial TV Sumaré</h1><p>Cadastre sua empresa, envie imagem/logo, telefone e link. A publicação passa por aprovação da TV Sumaré.</p></div><?php if($msg): ?><div class="ad-banner"><strong><?=h($msg)?></strong></div><?php endif; ?><div class="business-grid"><?php foreach($biz as $b): ?><article class="business-card"><span class="category-tag sponsored"><?=h($b['area']??'Empresa')?></span><h3><?=h($b['name']??'Empresa')?></h3><p><?=h($b['desc']??'')?></p><a class="btn btn-primary" href="https://wa.me/55<?=preg_replace('/\D/','',$b['phone']??'19974198194')?>" target="_blank">Chamar no WhatsApp</a></article><?php endforeach; ?></div><section class="box" style="margin-top:30px"><h2>Quero aparecer no Guia Comercial</h2><form method="post" enctype="multipart/form-data" class="filter-bar" style="display:grid;grid-template-columns:repeat(2,1fr);gap:14px"><input type="hidden" name="form_type" value="guia"><input name="company" required placeholder="Nome da empresa"><input name="category" required placeholder="Categoria"><input name="whatsapp" required placeholder="WhatsApp"><input name="city" placeholder="Cidade"><input name="address" placeholder="Endereço"><input name="instagram" placeholder="Instagram"><input name="link" placeholder="Site ou link"><textarea name="description" placeholder="Descrição da empresa" style="grid-column:1/-1"></textarea><label>Logo/imagem <input type="file" name="image" accept="image/*"></label><label>Comprovante PIX <input type="file" name="receipt" accept="image/*,application/pdf"></label><button class="btn btn-primary" type="submit">Enviar para aprovação</button></form></section></main><?php include 'rodape.php'; ?></body></html>
