<?php
require_once __DIR__ . '/auth.php';
require_login();
include dirname(__DIR__).'/config.php';
$nf = dirname(__DIR__) . '/data/noticias.json';
$news = file_exists($nf)?json_decode(file_get_contents($nf),true):[]; if(!is_array($news)) $news=[];
$id=$_GET['id']??''; $n=null; foreach($news as $item){ if(($item['id']??'')===$id) $n=$item; }
if(!$n){ http_response_code(404); echo 'Notícia não encontrada'; exit; }
$url=rtrim($site_url??'https://tvsumare.com.br','/').'/noticia.php?id='.urlencode($id);
$title=$n['title']??''; $city=$n['city']??'Sumaré e região'; $cat=$n['category']??'Notícias';
$caption="🚨 ".$title."\n\n".($n['subtitle']??'')."\n\n📍 ".$city."\n🗞️ Categoria: ".$cat."\n\nLeia a matéria completa no portal TV Sumaré:\n".$url."\n\n#TVSumaré #Sumaré #Paulínia #NovaOdessa #Hortolândia #Campinas #Americana #NotíciasDaRegião";
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Postar no Instagram</title><link rel="stylesheet" href="admin.css?v=6"><style>.post-preview{display:grid;grid-template-columns:360px 1fr;gap:18px}.insta-card{aspect-ratio:1/1;border-radius:24px;overflow:hidden;background:linear-gradient(135deg,#061a4d,#ff7a00);color:#fff;display:flex;flex-direction:column;justify-content:flex-end;padding:24px;box-shadow:0 20px 50px rgba(0,0,0,.2)}.insta-card img{width:120px;height:75px;object-fit:contain;background:#fff;border-radius:14px;padding:6px;margin-bottom:auto}.insta-card h2{font-size:25px;line-height:1.08;margin:18px 0 10px}.insta-card span{font-weight:900;letter-spacing:.08em;color:#ffd29e}.copybox{min-height:260px}@media(max-width:850px){.post-preview{grid-template-columns:1fr}}</style></head><body><div class="admin"><aside class="side"><div class="logo"><img src="../assets/logo-tv-sumare.jpeg" alt="TV Sumaré"><div><b>TV SUMARÉ</b><br><small>Painel Administrativo</small></div></div><nav class="menu"><a href="index.php">Dashboard</a><a href="noticias.php">Notícias publicadas</a><a href="drafts.php">Rascunhos</a><a href="monitor.php">Monitor + Gemini</a><a href="logout.php">Sair</a></nav></aside><main class="main"><div class="top"><div><span class="eyebrow">Redes sociais</span><h1>Postar no Instagram</h1></div><a class="btn secondary" href="noticias.php">Voltar</a></div><div class="post-preview"><div class="insta-card"><img src="../assets/logo-tv-sumare.jpeg" alt="TV Sumaré"><span><?=htmlspecialchars($cat)?></span><h2><?=htmlspecialchars($title)?></h2><p><?=htmlspecialchars($city)?> • Leia no portal</p></div><div class="box"><h2>Legenda pronta</h2><p>Copie a legenda abaixo e publique no Instagram. O Instagram não permite postagem automática direta por link simples em contas comuns; por isso este botão prepara o conteúdo pronto para copiar.</p><textarea class="copybox" id="caption"><?=htmlspecialchars($caption)?></textarea><div class="actions"><button class="btn orange" onclick="navigator.clipboard.writeText(document.getElementById('caption').value);alert('Legenda copiada!')">Copiar legenda</button><a class="btn" target="_blank" href="https://www.instagram.com/">Abrir Instagram</a><a class="btn secondary" target="_blank" href="<?=$url?>">Abrir matéria</a></div><p><small>Imagem sugerida: use a imagem destacada da matéria ou tire print do card ao lado. Para automação real de publicação no Instagram, será necessário Meta Business/Instagram Graph API.</small></p></div></div></main></div></body></html>
