<?php
include 'config.php';
require_once __DIR__.'/includes/tvs_public_helpers.php';
$active='noticias';
$news=tvs_json('data/noticias.json');
$news=function_exists('tvs_prepare_public_news_v2') ? tvs_prepare_public_news_v2((is_array($news)?$news:[]), 21) : tvs_prepare_public_news(is_array($news)?$news:[], 30);
$cat=trim($_GET['categoria']??'');
$q=trim($_GET['q']??'');
if($cat){ $news=array_values(array_filter($news, fn($n)=>tvs_lc($n['category']??'')===tvs_lc($cat))); }
if($q){ $news=array_values(array_filter($news, fn($n)=>stripos(($n['title']??'').' '.($n['subtitle']??'').' '.($n['body']??''),$q)!==false)); }
$cats=[''=>'Todas as categorias','Cidade'=>'Cidade','Política'=>'Política','Saúde'=>'Saúde','Educação'=>'Educação','Empregos'=>'Empregos','Esportes'=>'Esportes','Cultura'=>'Cultura','Segurança'=>'Segurança','Economia'=>'Economia','Brasil'=>'Brasil'];
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Notícias | TV Sumaré</title><meta name="description" content="Notícias regionais de Sumaré, Hortolândia, Paulínia, Nova Odessa, Americana e Campinas."><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/style.css?v=homologacao-final"><link rel="stylesheet" href="assets/tvsumare-final-fixes.css?v=3"></head><body><?php include 'header.php'; ?><main class="container page-shell"><div class="page-title"><span>Editorias</span><h1>Notícias da Região</h1><p>Busca, filtros por categoria e cobertura regional da TV Sumaré.</p></div><form class="filter-bar" method="get"><input name="q" value="<?=tvs_h($q)?>" type="search" placeholder="Buscar notícias, bairros, temas..."><select name="categoria" onchange="this.form.submit()"><?php foreach($cats as $value=>$label): ?><option value="<?=tvs_h($value)?>" <?=$value===$cat?'selected':''?>><?=tvs_h($label)?></option><?php endforeach; ?></select><button class="btn" type="submit">Buscar</button></form><div class="news-grid news-grid--wide"><?php if(!$news): ?><article class="news-card"><div class="news-body"><span class="category-tag">Portal</span><h3>Nenhuma notícia encontrada</h3><p>A redação está atualizando os conteúdos regionais.</p></div></article><?php endif; ?><?php foreach($news as $n): $img=tvs_display_image($n); ?><article class="news-card" data-card><div class="news-thumb"><img src="<?=tvs_h($img)?>" onerror="this.src='assets/tvsumare-noticia-padrao.svg'" alt=""></div><div class="news-body"><span class="category-tag"><?=tvs_h($n['category']??'Notícia')?></span><?php if(!empty($n['city'])):?><span class="category-tag"><?=tvs_h($n['city'])?></span><?php endif; ?><h3><?=tvs_h(tvs_title($n['title']??'Sem título',96))?></h3><p><?=tvs_h($n['subtitle']??tvs_excerpt_clean($n['summary']??$n['body']??'',140))?></p><a class="btn" href="<?=tvs_h(tvs_news_url($n))?>">Ler matéria</a></div></article><?php endforeach;?></div></main><?php include 'rodape.php'; ?></body></html>
