<?php
include 'config.php';
require_once __DIR__.'/includes/tvs_public_helpers.php';
$active='videos';
$videos=tvs_load_real_videos(0);
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vídeos | TV Sumaré</title><meta name="description" content="Vídeos, boletins e reportagens da TV Sumaré Play."><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/style.css?v=homologacao-final"><link rel="stylesheet" href="assets/tvsumare-final-fixes.css?v=3"><style>.public-video-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:22px}.public-video-card{background:#fff;border-radius:24px;padding:18px;box-shadow:var(--shadow);border:1px solid #e6edf8}.video-embed iframe,.video-embed video{width:100%;aspect-ratio:16/9;border:0;border-radius:18px;background:#000}.video-public-thumb{width:100%;aspect-ratio:16/9;object-fit:cover;border-radius:18px;background:#0f2f68}.video-thumb-placeholder{width:100%;aspect-ratio:16/9;display:flex;align-items:center;justify-content:center;border-radius:18px;background:linear-gradient(135deg,#0f2f68,#1d4ed8);color:#fff;font-size:44px;font-weight:900}.video-meta{font-size:13px;color:#64748b;font-weight:800;margin:8px 0}.video-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px}</style></head><body><?php include 'header.php'; ?><main class="container page-shell"><div class="page-title"><span>TV Sumaré Play</span><h1>Vídeos, Reportagens e Boletins</h1><p>Assista aos conteúdos publicados pela TV Sumaré. Esta página exibe apenas vídeos reais cadastrados ou gerados pela plataforma.</p></div>
<?php if(!$videos): ?><div class="empty-state"><h2>Nenhum vídeo ativo no momento</h2><p>Quando houver vídeos publicados, eles aparecerão automaticamente nesta página.</p></div><?php else: ?>
<div class="video-grid public-video-grid">
<?php foreach($videos as $v): $url=tvs_video_url($v); $embed=tvs_youtube_embed($url); $thumb=tvs_video_thumb($v); ?>
<article class="video-card public-video-card"><span class="category-tag"><?=tvs_h($v['category']??'Vídeo')?></span><?php if(!empty($v['city'])):?><span class="category-tag"><?=tvs_h($v['city'])?></span><?php endif; ?><h3><?=tvs_h($v['title']??'Vídeo TV Sumaré')?></h3><div class="video-meta"><?=tvs_h(date('d/m/Y H:i',tvs_date_ts($v)))?></div><?php if($embed): ?><div class="video-embed"><iframe src="<?=tvs_h($embed)?>" title="<?=tvs_h($v['title']??'Vídeo')?>" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><?php elseif(preg_match('~\.mp4(\?|$)~i',$url)): ?><div class="video-embed"><video controls playsinline src="<?=tvs_h($url)?>" poster="<?=tvs_h($thumb)?>"></video></div><?php else: ?><a href="<?=tvs_h($url)?>" target="_blank" rel="noopener"><?php if($thumb): ?><img class="video-public-thumb" src="<?=tvs_h($thumb)?>" onerror="this.outerHTML='<div class=&quot;video-thumb-placeholder&quot;>▶</div>'" alt=""><?php else: ?><div class="video-thumb-placeholder">▶</div><?php endif; ?></a><?php endif; ?><p><?=tvs_h(tvs_excerpt($v['description']??$v['script']??'Conteúdo em vídeo da TV Sumaré.',180))?></p><div class="video-actions"><a class="btn" href="<?=tvs_h($url)?>" target="_blank" rel="noopener">Abrir vídeo</a><?php if(!empty($v['news_id'])):?><a class="btn btn-outline" href="noticia.php?id=<?=urlencode($v['news_id'])?>">Ver notícia</a><?php endif; ?></div></article>
<?php endforeach; ?>
</div><?php endif; ?></main><?php include 'rodape.php'; ?></body></html>
