server {
  listen 80;
  server_name _;
  location = /health {
    add_header Content-Type application/json;
    return 200 '{"ok":true,"service":"projeto-lucas-hml","mode":"homologation"}';
  }
  location / {
    root /usr/share/nginx/html;
    try_files $uri /index.html;
  }
}
